const courses=[
{id:"drawing",title:"Академический рисунок",desc:"Линия, форма, перспектива, конструкция, светотень и натюрморт.",level:"Beginner",lessons:12},
{id:"composition",title:"Архитектурная композиция",desc:"Ритм, масштаб, пропорции, баланс, контраст, симметрия и центр.",level:"Beginner",lessons:10},
{id:"drafting",title:"Черчение",desc:"Проекции, виды, разрезы, аксонометрия, перспектива и масштабы.",level:"Intermediate",lessons:14}];
const lessons={
drawing:["Основы перспективы","Геометрические тела","Конструкция формы","Светотень","Практическая работа"],
composition:["Композиционный центр","Ритм и повтор","Масштаб и пропорции","Баланс и контраст","Практическая композиция"],
drafting:["Ортогональные проекции","Виды и разрезы","Аксонометрия","Масштабы","Практическое черчение"]};
const exercises=[
{id:"cube",cat:"Черчение",title:"Построение куба в перспективе",level:"Beginner",time:"30 минут",skill:"Перспектива",desc:"Построй куб в двухточечной перспективе, соблюдая вертикали и точки схода."},
{id:"composition",cat:"Композиция",title:"Ритм из простых форм",level:"Beginner",time:"40 минут",skill:"Ритм",desc:"Создай композицию из трёх геометрических элементов с выраженным ритмом."},
{id:"still",cat:"Рисунок",title:"Гипсовый натюрморт: конструкция",level:"Intermediate",time:"60 минут",skill:"Конструкция",desc:"Разбери предметы на простые геометрические формы и построй их конструктивно."},
{id:"section",cat:"Черчение",title:"Простой архитектурный разрез",level:"Intermediate",time:"45 минут",skill:"Разрез",desc:"Выполни разрез небольшого двухэтажного объёма с обозначением основных элементов."}];
const materials=[];
const questions=[
{cat:"Рисунок",q:"Какие линии в перспективе обычно направляются к одной точке схода?",a:["Горизонтальные на листе","Параллельные пространственные направления","Все вертикальные линии","Оси симметрии"],c:1},
{cat:"Композиция",q:"Что называют композиционным центром?",a:["Самую маленькую деталь","Элемент или область, привлекающую основное внимание","Только геометрический центр листа","Рамку изображения"],c:1},
{cat:"История",q:"Кто создал Fallingwater (Дом над водопадом)?",a:["Ле Корбюзье","Фрэнк Ллойд Райт","Мис ван дер Роэ","Антонио Гауди"],c:1},
{cat:"Черчение",q:"Как называется изображение предмета после мысленного рассечения?",a:["Фасад","План","Разрез","Эскиз"],c:2},
{cat:"История",q:"Какое направление связано с лозунгом функциональности и слиянием искусства, дизайна и производства?",a:["Барокко","Баухаус","Рококо","Романика"],c:1},
{cat:"Композиция",q:"Что такое ритм в композиции?",a:["Случайное размещение объектов","Закономерное повторение и чередование элементов","Только симметрия","Размер листа"],c:1},
{cat:"Черчение",q:"Масштаб 1:100 означает, что 1 см на чертеже соответствует:",a:["1 мм в натуре","10 см в натуре","1 м в натуре","100 м в натуре"],c:2},
{cat:"Рисунок",q:"Что прежде всего помогает понять конструкцию формы?",a:["Случайная штриховка","Построение основных объёмов и осей","Яркий цвет","Рамка"],c:1}];

function getProgress(){return JSON.parse(localStorage.getItem("archprep_progress")||"{}")}
function setProgress(p){localStorage.setItem("archprep_progress",JSON.stringify(p))}
function track(e){const a=JSON.parse(localStorage.getItem("archprep_events")||"[]");a.push({event:e,time:new Date().toISOString()});localStorage.setItem("archprep_events",JSON.stringify(a))}
track("page_view");
function coursePct(id){const p=getProgress(); return p.courses?.[id]||0}
function courseCard(c){return `<a class="course-card" href="course.html?id=${c.id}"><div class="course-art"><span>${String(courses.indexOf(c)+1).padStart(2,"0")}</span><i></i></div><div class="meta"><span>${c.level}</span><span>${c.lessons} уроков</span></div><h3>${c.title}</h3><p>${c.desc}</p><b>Начать →</b></a>`}
function renderCourses(){let el=document.getElementById("all-courses")||document.getElementById("featured-courses");if(el)el.innerHTML=courses.map(courseCard).join("")}
function renderCourse(){const el=document.getElementById("course-detail");if(!el)return;const id=new URLSearchParams(location.search).get("id")||"drawing",c=courses.find(x=>x.id===id)||courses[0],pct=coursePct(id),ls=lessons[id]||[];el.innerHTML=`<section class="course-head"><p class="eyebrow">COURSE / ${String(courses.indexOf(c)+1).padStart(2,"0")}</p><h1>${c.title}</h1><p class="lead">${c.desc}</p><div class="course-progress"><div><span>Ваш прогресс</span><b>${pct}%</b></div><div class="progressbar"><i style="width:${pct}%"></i></div></div></section><section class="section lesson-section"><div class="section-head"><span>LESSONS</span><h2>Программа</h2></div><div class="lesson-list">${ls.map((l,i)=>`<div class="lesson"><span>${String(i+1).padStart(2,"0")}</span><div><h3>${l}</h3><small>${i<pct/100*ls.length?"Завершён":"Не начат"}</small></div><button data-lesson="${i}" data-course="${id}">${i<pct/100*ls.length?"✓":"Открыть"} </button></div>`).join("")}</div></section>`;el.querySelectorAll("[data-lesson]").forEach(btn=>btn.onclick=()=>{let p=getProgress();p.courses=p.courses||{};p.courses[id]=Math.min(100,Math.round(Math.max(p.courses[id]||0,(+btn.dataset.lesson+1)/ls.length*100)));setProgress(p);track("lesson_completed");location.reload()})}
function renderExercises(){const el=document.getElementById("exercises");if(!el)return;const draw=cat=>{el.innerHTML=exercises.filter(x=>cat==="all"||x.cat===cat).map((x,i)=>`<a class="exercise-row" href="exercise.html?id=${x.id}"><span>0${i+1}</span><div><small>${x.cat} / ${x.level}</small><h3>${x.title}</h3><p>${x.desc}</p></div><div class="exercise-meta"><span>${x.time}</span><span>${x.skill}</span><b>Открыть →</b></div></a>`).join("")};draw("all");document.querySelectorAll(".filter").forEach(b=>b.onclick=()=>{document.querySelectorAll(".filter").forEach(x=>x.classList.remove("active"));b.classList.add("active");draw(b.dataset.filter)})}
function renderExercise(){const el=document.getElementById("exercise-detail");if(!el)return;const id=new URLSearchParams(location.search).get("id")||"cube",x=exercises.find(a=>a.id===id)||exercises[0];el.innerHTML=`<section class="page-hero"><p class="eyebrow">${x.cat} / ${x.level} / ${x.time}</p><h1>${x.title}</h1><p class="lead">${x.desc}</p></section><section class="section exercise-detail"><div class="task-box"><p class="eyebrow">TASK</p><h2>Условие</h2><p>${x.desc} Работай аккуратно, сначала проверь пропорции и конструкцию, затем добавляй детали.</p><h2>Рекомендации</h2><ol><li>Разметь лист и основные оси.</li><li>Проверь перспективу и пропорции.</li><li>Только после построения переходи к тону и деталям.</li></ol><button id="done-exercise" class="button button-dark">Отметить как выполненное ✓</button></div><div class="upload-box"><span>WORK / UPLOAD</span><h3>Загрузить работу</h3><p>В первой версии можно выбрать файл. Подключение хранилища добавляется на backend.</p><input type="file" accept="image/*,.pdf"><a class="text-link" href="https://www.youtube.com/" target="_blank">Посмотреть видео-разбор →</a></div></div></section>`;document.getElementById("done-exercise").onclick=()=>{let p=getProgress();p.exercises=p.exercises||{};p.exercises[id]=true;setProgress(p);track("exercise_completed");alert("Задание отмечено как выполненное.");}}
function renderProgress(){const s=document.getElementById("stats");if(!s)return;const p=getProgress(),doneC=Object.values(p.courses||{}).filter(x=>x>=100).length,doneE=Object.keys(p.exercises||{}).length,results=JSON.parse(localStorage.getItem("archprep_results")||"[]"),avg=results.length?Math.round(results.reduce((a,b)=>a+b.score,0)/results.length):0;s.innerHTML=`<div><span>Завершённых курсов</span><b>${doneC}</b></div><div><span>Выполненных заданий</span><b>${doneE}</b></div><div><span>Пройденных тестов</span><b>${results.length}</b></div><div><span>Средний результат</span><b>${avg}%</b></div>`;document.getElementById("progress-courses").innerHTML=courses.map(c=>`<div class="progress-course"><div><span>${c.title}</span><b>${coursePct(c.id)}%</b></div><div class="progressbar"><i style="width:${coursePct(c.id)}%"></i></div></div>`).join("")}
renderCourses();renderCourse();renderExercises();renderExercise();renderProgress();renderQuiz();
document.querySelector(".menu-toggle")?.addEventListener("click",()=>document.querySelector("nav").classList.toggle("open"));
